# Generated by Django 2.2 on 2020-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email_address', models.EmailField(max_length=254)),
                ('educ_background', models.TextField(verbose_name='Educational Background')),
                ('position', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100, null=True, verbose_name=' Phone Contact')),
                ('experience', models.TextField()),
                ('publication', models.TextField()),
                ('other', models.TextField(max_length=500)),
                ('training', models.TextField(verbose_name='Training or Certifications')),
                ('ref_1_phone', models.CharField(max_length=100, null=True, verbose_name='Referees Phone Contact')),
                ('ref_2_name', models.CharField(max_length=100, null=True, verbose_name='Referees Full Name')),
                ('ref_1_name', models.CharField(max_length=100, null=True, verbose_name='Referees Phone Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_deadline_date', models.DateField()),
                ('details_link', models.URLField(max_length=255)),
                ('vacancy', models.IntegerField()),
            ],
        ),
    ]
