# Generated by Django 2.2 on 2020-03-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='other_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='publication',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='training',
            field=models.TextField(blank=True, verbose_name='Training or Certifications'),
        ),
    ]
