# Generated by Django 2.2 on 2020-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200313_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
