# Generated by Django 2.2 on 2020-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200313_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
