# Generated by Django 2.2 on 2020-03-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200313_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ref_1_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ref_1_phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ref_2_name',
        ),
    ]
