# Generated by Django 2.2 on 2020-03-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200313_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='other',
        ),
    ]
